### ISSUE TITLE
functions.js can be improved

### ISSUE THREAD

**Issue by aleemulhaq** [5PK/hold-em#5]
Currently functions.js includes a getLobbyCode() function which generates a 5 string code from 2 arrays.

I am proposing using math.random to generate 5 unique chars and verifying those are truly unique by comparing with existing codes.

**Comment by aleemulhaq** [comment]
assign to me please

**Comment by 5PK** [comment]
closed in [this PR](https://github.com/5PK/hold-em/pull/6)
